name: Email Reader Build
on: [push]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Allow permission to gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew build
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Allow permission to gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew test