name: Email Reader Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: apt install openjdk-11-jre-headless
      - run: cd ${{ github.workspace }}
      - run: chmod +x gradlew
#      - run: ./gradlew --stacktrace build
